### ISSUE TITLE
module :http_uri not available in OTP release

### ISSUE THREAD

**Issue by seanpascoe** [achedeuzot/ecto_commons#66]
I'm using the `URLValidator.validate_url` function and it works great in development. I created a phoenix production release and it is erroring at that function with `** (UndefinedFunctionError) function :http_uri.parse/1 is undefined (module :http_uri is not available)`. I'm fairly new to elixir and I'm having a hard time figuring out why that erlang module wouldn't be available in the release.

**Comment by aparod** [comment]
You're probably running different versions of Erlang between your dev and prod environments.  I'm on Erlang/OTP 24 and it gives me a warning that `:http_uri.parse/1` is deprecated and will be removed in OTP 25.

**Comment by achedeuzot** [comment]
Hm indeed, it looks like a difference in OTP versions. Thanks @aparod ❤️ 
We'll have to look for a replacement of the `:http_uri.parse` function for this validator for OTP > 25.

**Comment by HangingClowns** [comment]
What about `URI.new/1` in Elixir?

**Comment by allenwyma** [comment]
hi @achedeuzot its' been quite some time and this issue still isn't resolved. I've also noticed you have quite a few dependabot PRs waiting to be updated.

Did you need some help with this project?

**Comment by achedeuzot** [comment]
@allenwyma I'd be happy to have a hand on it indeed, I've been quite busy lately so I've struggled to find time to maintain this even tough I still use it in production.

**Comment by allenwyma** [comment]
I'm more than happy to help out on this cause I'd hate to see such a useful package stalled out due to someone being busy. :)

**Comment by allenwyma** [comment]
@achedeuzot as a workaround, erlang uses to use `:uri_string`, so I was looking at `:uri_string.parse/1` but these URIs are failing in the test to be marked as false:

```
rdar://1234
h:/test
ftps://foo.bar/
```

**Comment by achedeuzot** [comment]
They do look false though, don't they ? Well we can set them as truthy but it might provide a less strict validation which could have unintended consequences on end-users of the lib :/ This option would probably require a lib major version bump so users are aware of the breaking change.

What about using `URI.parse/1` ?

**Comment by allenwyma** [comment]
URI.parse/1 will parse anything:
```
iex> URI.parse("foo/bar")
%URI{
  fragment: nil,
  host: nil,
  path: "foo/bar",
  port: nil,
  query: nil,
  scheme: nil,
  userinfo: nil
}
```

**Comment by allenwyma** [comment]
@achedeuzot let me know what you think of #88 

I went back and looked at the code for http_uri and looks like they hard checked for certain ports if they are there or not, which is what i tried to emulate.

**Comment by achedeuzot** [comment]
#88 looks good :) 

I'm just a bit unsure of using `uri_string ` vs `URI.parse`, WDYT is more future proof ?

**Comment by allenwyma** [comment]
replaced with URI.parse/1 and seems to work fine, at least for the tests.

**Comment by achedeuzot** [comment]
Looks good with `URI.parse/1` :) 
It seems the CI script will need a bit of a refresher too for erlang / elixir compatibility matrix.

**Comment by allenwyma** [comment]
@achedeuzot no idea how this stuff works, can you take a moment to try to fix that?

**Comment by joeyates** [comment]
Hi @achedeuzot (pinging also @allenwyma and @esacteksab)

I'd be willing to sort out the URI stuff and the CI matrix, but I think it would be a good idea to clarify a couple of things first...

### URI Parsing

Firstly, `uri_string` is not available in all OTP versions: "[Module uri_string was introduced in OTP 21.0](https://www.erlang.org/doc/man/uri_string#since)"

Secondly, it is not possible to specify a minimum OTP version in `mix.exs` - it's an [explicit policy](https://elixirforum.com/t/specifying-minimal-erlang-version-in-mix-exs/39911/3).

But, `URI.parse/1` [has been around since well before Elixir 1.9.0](https://hexdocs.pm/elixir/1.9.0/URI.html#parse/1). And this library [declares 1.9 as it's minimal supported version](https://github.com/achedeuzot/ecto_commons/blob/master/mix.exs#L15).

So, I think the best way forward with URI parsing is to switch to using Elixir's `URI.parse/1`.

### Build Matrix

The [current CI configuration](https://github.com/achedeuzot/ecto_commons/blob/5101aa72b470500425b26c96b2e867393a2f38e3/.github/workflows/main.yaml#L20) runs `3*4 - 5` = 7 builds.

In comparison, [Ecto runs 3](https://github.com/elixir-ecto/ecto/blob/3f1b1a63cac5bb79f6fc00071e38db2658bcc04b/.github/workflows/ci.yml#L22).

I propose reducing down to 3. I would keep the same minimum versions as now (Elixir 1.9.4 and OTP 20.3), plus the latest releases of both (currently Elixir 1.16.0 and OTP 26.2.1) plus one more in the middle (Elixir 1.13, OTP 23).

**Comment by joeyates** [comment]
Additional note: it would be necessary to implement the failure cases of `http_uri.parse/1` as `URI.parse/1` accepts any String.

**Comment by achedeuzot** [comment]
Hi @joeyates 👋

I haven't had the time lately to give this lib the love it deserves. I'm happy to merge PRs that fix or improve the CI as well as the compatibility matrix and support :)

**Comment by joeyates** [comment]
I've made a PR (https://github.com/achedeuzot/ecto_commons/pull/90) with the introduction of `URI.new/1` to **replace** calls to the OTP function `:http_uri.parse/1`.

**Comment by achedeuzot** [comment]
All the pending pull requests have been merged and/or the corresponding issue fixed.
There's a new release: 0.3.5 🎉

Thank you all for your contributions ❤️🤗
